config/routes.rb
Rails.application.routes.draw do
  resources :inventories, except: :show do
    resources :items
    resources :locations
  end
  
  root "inventories#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/inventory.rb
class Inventory < ApplicationRecord
  has_many :locations, dependent: :destroy
  has_one :base_location, -> { where(base: true) }, 
    class_name: "Location"

  has_many :items, dependent: :destroy
  validates :name, presence: true

  accepts_nested_attributes_for :base_location

  def change_base_location_to(new_base_location)
    Inventory.trasaction do 
      base_location.update(base: false)
      new_base_location.update(base: true)
    end

    base_location
  end
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :inventory
  validates :name, :quantity, presence: true
end

app/models/location.rb
class Location < ApplicationRecord
  belongs_to :inventory
  
  validates :name, :address, :city, :country, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/inventories_controller.rb
class InventoriesController < ApplicationController
  
  def index
    @inventories = Inventory.all
  end

  def new
    @inventory = Inventory.new

    @inventory.build_base_location
  end

  def edit
    @inventory = Inventory.find(params[:id])
  end

  def create
    @inventory = Inventory.create(inventory_params)

    if @inventory.save
      redirect_to inventories_path
    else 
      render :new, status: :unprocessable_entity
    end
  end

  def update
    @inventory = Inventory.find(params[:id])

    if @inventory.update(inventory_params)
      redirect_to inventories_path
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @inventory = Inventory.find(params[:id])
    
    @inventor.destroy

    redirect_to inventories_path, status: :see_other
  end

  private
    def inventory_params
      params.required(:inventory).permit(:id, :name, base_location_attributes: [:id, :name, :address, :city, :country])
    end
end

app/controllers/inventory_controller.rb
class InventoryController < ApplicationController
  
  def index

  end

  def new

  end

  def edit

  end

  def create

  end

  def update

  end

  def destroy

  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

  def index
    @inventory = Inventory.find(params[:inventory_id])
    @items = @inventory.items.all
  end

  def show
    @item = Item.find(params[:id])
    @inventory = Inventory.find(params[:inventory_id])
  end

  def new
    @inventory = Inventory.find(params[:inventory_id])
    @item = @inventory.items.build
  end

  def edit
    @inventory = Inventory.find(params[:inventory_id])
    @item = Item.find(params[:id])
  end

  def create
    @inventory = Inventory.find(params[:inventory_id])
    @item = @inventory.items.build(item_params)

    if @item.save
      redirect_to inventory_items_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    @inventory = Inventory.find(params[:inventory_id])
    @item = Item.find(params[:id])
    
    if @item.update(item_params)
      redirect_to inventory_item_path(@inventory, @item)
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @item = Item.find(params[:id])

    @item.destroy 

    redirect_to inventory_items_path
  end

  private
    def item_params 
      params.required(:item).permit(:id, :name, :quantity)
    end
end

app/controllers/location_controller.rb
class LocationController < ApplicationController
  
  def index

  end

  def show

  end

  def new

  end
  
  def edit

  end

  def create

  end
  
  def update

  end
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  
  def index
    @inventory = Inventory.find(params[:inventory_id])
    @locations = @inventory.locations.all
  end

  def show
    @inventory = Inventory.find(params[:inventory_id])
    @location = @inventory.locations.find(params[:id])
  end

  def new
    @inventory = Inventory.find(params[:inventory_id])
    @location = @inventory.locations.build
  end
  
  def edit
    @inventory = Inventory.find(params[:inventory_id])
    @location = Location.find(params[:id])
  end

  def create
    @inventory = Inventory.find(params[:inventory_id])
    @location = @inventory.locations.build(location_params)

    if @location.save
      redirect_to inventory_locations_path
    else
      render :new, status: :unporcessable_entity
    end
  end
  
  def update
    @location = Location.find(params[:id])

    if @location.update(location_params)
      redirect_to inventory_locations_path
    else 
      render :edit, status: :unprocessable_entity
    end
  end

  private
    def location_params 
      params.required(:location).permit(:id, :name, :address, :city, :country)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/inventory_helper.rb
module InventoryHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/location_helper.rb
module LocationHelper
end

app/views/inventories/_form.html.erb
<%= form_with model: @inventory do |inventory_form| %>
  <%= inventory_form.label :name %>
  <%= inventory_form.text_field :name %><br>

  <% if @inventory.persisted? %>
    <%= inventory_form.label :base_location_id, "Base Location" %>
    <%= inventory_form.select :base_location, options_from_collection_for_select(@inventory.locations, "id", "name", @inventory.base_location.id), {} %><br>
  <% else %>
    <h1>
    Inventory
    </h1>
    <%= inventory_form.fields_for :base_location, @inventory.base_location do |location_fields| %>

      <%= location_fields.label :name %>
      <%= location_fields.text_field :name %><br>

      <%= location_fields.label :address %>
      <%= location_fields.text_field :address %><br>

      <%= location_fields.label :city %>
      <%= location_fields.text_field :city %><br>

      <%= location_fields.label :country %>
      <%= location_fields.text_field :country %>
    <% end %>
  <% end %>
<%= inventory_form.submit %>
<% end %>

app/views/inventories/_inventory.html.erb
<div class="relative overflow-x-auto shadow-md">
    <table class="w-full text-sm text-left text-gray-500 dark:text-gray-400">
        <tbody>
            <tr class="border-b dark:bg-gray-800 dark:border-gray-700 odd:bg-white even:bg-gray-50 odd:dark:bg-gray-800 even:dark:bg-gray-700">
                <th scope="row" class="px-6 py-4 font-medium text-gray-900 dark:text-white whitespace-nowrap">
                  <%= link_to inventory.name, inventory_items_path(inventory) %>
                </th>

                <td class="px-6 py-4 text-right">
                  <%= link_to "Edit", edit_inventory_path(inventory), class:"font-medium text-blue-600 dark:text-blue-500 hover:underline" %>
                </td>

                <td class="px-6 py-4 text-right">
                  <%= link_to "Manage Locations", inventory_locations_path(inventory) %>
                </td>
            </tr>
        </tbody>
    </table>
</div>

app/views/inventories/edit.html.erb
<h1>
  Edit
</h1>

<%= render "form" %>

app/views/inventories/index.html.erb
<%= render @inventories %>


<%= render "shared/fab", url: new_inventory_path, model_name: "inventory" %>

app/views/inventories/new.html.erb
<h1>
  Add Inventory
</h1>

<%= render "form" %>

app/views/items/_form.html.erb
<%= form_with model: [@inventory, @item] do |item_form| %>

  <%= item_form.label :name %>
  <%= item_form.text_field :name %> <br>

  <%= item_form.label :quantity %>
  <%= item_form.number_field :quantity %><br>

  <%= item_form.submit %>

<% end %>

app/views/items/_item.html.erb
<div class="relative overflow-x-auto shadow-md">
  <table class="w-full text-sm text-left text-gray-500 dark:text-gray-400">
    <thead class="text-xs text-gray-700 uppercase bg-gray-50 dark:bg-gray-700 dark:text-gray-400">
    </thead>
    <tbody>
      <tr class="border-b dark:bg-gray-800 dark:border-gray-700 odd:bg-white even:bg-gray-50 odd:dark:bg-gray-800 even:dark:bg-gray-700">
        <th scope="row" class="px-6 py-4 font-medium text-gray-900 dark:text-white whitespace-nowrap">
          <%= link_to item.name, inventory_item_path(item.inventory, item) %>
        </th>
        </td>
        <td class="px-6 py-4 text-right">
          <%= link_to "Edit", edit_inventory_item_path(item.inventory, item), class:"font-medium text-blue-600 dark:text-blue-500 hover:underline" %>
        </td>
      </tr>
  </table>
</div>

app/views/items/edit.html.erb
<h1>
  Edit Item
</h1>

<%= render "form" %>

app/views/items/index.html.erb
<%= render @items %>

<%= render "shared/fab", url: new_inventory_item_path, model_name: "item" %>

app/views/items/new.html.erb
<h1> Add Item </h1>

<%= render "form" %>

app/views/items/show.html.erb
<h1>
  Description
</h1>

<b>Item Name:</b> <%= @item.name %>
<b>Item Quantity:</b> <%= @item.name %>

<%= link_to "Back to Items", inventory_items_path %>

app/views/layouts/_navbar.html.erb
<nav class="flex items-center justify-between flex-wrap bg-teal-500 p-6">
  <div class="flex items-center flex-shrink-0 text-white mr-6">
    <span class="font-semibold text-xl tracking-tight"><%= link_to "Inventory Tracking App", root_path %></span>
  </div>
  <div class="block lg:hidden">
    <button class="flex items-center px-3 py-2 border rounded text-teal-200 border-teal-400 hover:text-white hover:border-white">
      <svg class="fill-current h-3 w-3" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><title>Menu</title><path d="M0 3h20v2H0V3zm0 6h20v2H0V9zm0 6h20v2H0v-2z"/></svg>
    </button>
  </div>
  <div class="w-full block flex-grow lg:flex lg:items-center lg:w-auto">
    <div class="text-sm lg:flex-grow">
      </a>
    </div>
    <div>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>InventoryTrackerApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

    <link href="https://fonts.gstatic.com" rel="preconnect" crossorigin>
    <%= stylesheet_link_tag "https://fonts.googleapis.com/icon?family=Material+Icons" %>
  </head>

  <body>
    <%= render "layouts/navbar" %>
    <%= yield %>
    <% debug(params) if Rails.env.development? %>
  </body>
</html>

app/views/locations/_form.html.erb
<%= form_with model: [@inventory, @location] do |location_form| %>

  <%= location_form.label :name %>
  <%= location_form.text_field :name %><br>

  <%= location_form.label :address %>
  <%= location_form.text_field :address %><br>

  <%= location_form.label :city %>
  <%= location_form.text_field :city %><br>

  <%= location_form.label :country %>
  <%= location_form.text_field :country %><br>

  <%= location_form.submit %>

<% end %>



  

app/views/locations/edit.html.erb
<h1>
  Edit Location
</h1>

<%= render "form" %>

app/views/locations/index.html.erb
<h1>
  Manage Locations
</h1>


<%= render "shared/fab", url: new_inventory_location_path, model_name: "location" %>

app/views/locations/new.html.erb
<h1>
  Add Location
</h1>

<%= render "form" %>

app/views/locations/show.html.erb
<div class="bg-white shadow overflow-hidden sm:rounded-lg">
  <div class="px-4 py-5 sm:px-6">
    <h3 class="text-lg leading-6 font-medium text-gray-900">Location Details</h3>
    <p class="mt-1 max-w-2xl text-sm text-gray-500">Address and Location.</p>
  </div>
  <div class="border-t border-gray-200">
    <dl>
      <div class="bg-gray-50 px-4 py-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6">
        <dt class="text-sm font-medium text-gray-500">Name</dt>
        <dd class="mt-1 text-sm text-gray-900 sm:mt-0 sm:col-span-2"><%= @location.name %> </dd>
      </div>
      <div class="bg-white px-4 py-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6">
        <dt class="text-sm font-medium text-gray-500">Address</dt>
        <dd class="mt-1 text-sm text-gray-900 sm:mt-0 sm:col-span-2"><%= @location.address %></dd>
      </div>
      <div class="bg-gray-50 px-4 py-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6">
        <dt class="text-sm font-medium text-gray-500">City</dt>
        <dd class="mt-1 text-sm text-gray-900 sm:mt-0 sm:col-span-2"><%= @location.city %></dd>
      </div>
      <div class="bg-white px-4 py-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6">
        <dt class="text-sm font-medium text-gray-500">Country</dt>
        <dd class="mt-1 text-sm text-gray-900 sm:mt-0 sm:col-span-2"><%= @location.country %></dd>
      </div>
    </dl>
  </div>
</div>

app/views/shared/_fab.html.erb
<%= button_to url, method: :get, id: "add_#{model_name}" do %>
  <div class="flex start-end items-center justify-center flex-wrap bg-teal-500 p-6 text-blue-700">
    <span class="material-icons">add</span>
  </div>
<% end %>